version: "3.7"

services:
  # db:
  #   container_name: 'chat_history_db'
  #   image: 'postgres:latest'
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - 'POSTGRES_USER=postgres'
  #     - 'POSTGRES_PASSWORD=password'
  #     - 'POSTGRES_DB=chat_history_db'
  server:
    container_name: "chat_server"
    image: "chat_server"
    ports:
      - "8080:8080"
  ui:
    container_name: "chat_ui"
    image: "chat_ui"
    ports:
      - "3000:3000"
  load_balancer:
    container_name: "load_balancer"
    image: "load_balancer"
    ports:
      - "8081:8080"
